name: API Tests with Postman and Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman + HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          newman run RegressionTesting.postman_collection.json \
           1--env-var baseUrl="${{ secrets.BASE_URL }}" \
            --reporters cli,junit,htmlextra \
            --reporter-junit-export results/junit-report.xml \
            --reporter-htmlextra-export results/html-report.html \
            --reporter-htmlextra-title "API Test Report - Login Tests"

      # Upload HTML report for download
      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: results/html-report.html


