name: API Tests with Postman and Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run your-collection.json \
          -e your-environment.json \
          --reporters cli,junit \
          --reporter-junit-export results/junit-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: results/junit-report.xml
